name = "math"
version = "0.1.0"
defaultTargets = ["math"]


[[require]]
name = "batteries"
scope = "leanprover-community"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
scope = "leanprover"
name = "doc-gen4"
# If you are developing against a release candidate or a stable version `v4.x`, replace `main` below by `v4.x`.
# If you do not use `main` keep in mind to update this field as you update your Lean version.
rev = "main"

[[lean_lib]]
name = "Math"

[[lean_exe]]
name = "math"
root = "Main"
